version: '3'
services:
  redisearch:
    image: "redislabs/redisearch:1.4.18"
    ports:
      - "6379:6379"
  beerloader:
    build: ./beerloader/.
    depends_on:
      - redisearch
    command: ['import.py', '--url', 'redis://redisearch:6379']
  frontend:
    build: ./frontend/.
    ports:
      - "5000:5000"
    depends_on:
      - redisearch
      - beerloader
