name: CI

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run the docker-compose
      run: docker-compose up -d
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: Check running containers
      run: docker ps
    - name: Test
      run: |
        cd test
        pip install -r requirements.txt
        python test.py
        
    - name: action-slack
      uses: 8398a7/action-slack@v2.7.0
      with:
          status: ${{ job.status }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
