name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run the Docker image
      run: docker-compose up
    - name: Test
      run: |
        cd test
        pip install -r requirements.txt
        python test.py
